# Generated by Django 5.0.3 on 2024-05-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_like_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='content',
            field=models.TextField(default='Reel Content'),
        ),
    ]
