# Generated by Django 5.0.3 on 2024-05-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_messge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messge',
            new_name='Message',
        ),
    ]
