# Generated by Django 5.0.2 on 2024-03-17 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_confirmation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_loged_in',
            field=models.BooleanField(null=True),
        ),
    ]
