# Generated by Django 5.0.2 on 2024-02-28 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_confirmation_code_user_is_confirmed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_loged_in',
        ),
    ]
